*ptn1start
[bg storage="bg1.jpg" layer=base time=500]
[cm]
単純な分岐[r]
[eval exp="f.変数１=10"]
[eval exp="f.変数２=10"]
[eval exp="f.変数３=0"]
変数１の値は[emb exp="f.変数１"][r]
変数２の値は[emb exp="f.変数２"][l][r]
[if exp="f.変数１==10"]
	[eval exp="f.変数３=f.変数１*f.変数２"]
	条件判断は「真」なので、変数３は[r]
	[emb exp="f.変数３"][l][r]
[else]
	[eval exp="f.変数３=0"]
	条件判断は「偽」なので、変数３は[r]
	[emb exp="f.変数３"][l][r]
[endif]
[link storage="lesson1.ks" target=*L1Start]この書き方、覚えてね！[endlink][r]
[link storage="first.ks" target=*fstart]最初に戻る[endlink]